### ISSUE TITLE
mirrors.lst has line breaks in DOS/Windows format

### ISSUE THREAD

**Issue by vcatafesta** [void-linux/xmirror#15]
the file https://xmirror.voidlinux.org/raw/mirrors.lst is stored with line breaks in DOS/Windows format

**Comment by classabbyamp** [comment]
does that break something?

**Comment by vcatafesta** [comment]
> does that break something?

Yes, xmirror and other software already written for this purpose, it is necessary to convert not to break when reading in Linux
